<a href="https://colab.research.google.com/github/sabbir-ahmed12/pytorch-practice/blob/main/basic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Basics**
- Tensor initialization and manipulation.

In [1]:
import torch

### **Setting up device**

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

### **Tensor Initialization**

In [3]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, )
print(X)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
# Printing the data type
print(X.dtype)

torch.float32


In [5]:
# Printing the shape
print(X.shape)

torch.Size([2, 3])


In [6]:
# Printing if gradient is required
print(X.requires_grad)

False


**Empty Initialization (Random)**

In [7]:
X = torch.empty(size=(3, 3))
print(X)

tensor([[2.4202e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.5554e-43],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


**Zero Initialization**

In [9]:
X = torch.zeros((3, 3))
print(X)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**Random initialization from uniform distribution**

In [10]:
X = torch.rand((3, 3))
print(X)

tensor([[0.9513, 0.6735, 0.3245],
        [0.2420, 0.7076, 0.9891],
        [0.3853, 0.6069, 0.3909]])


**Ones Initialization**

In [11]:
X = torch.ones((3, 3))
print(X)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


**Identity Matrix**

In [13]:
X = torch.eye(3, 3)
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Some other methods**

In [14]:
X = torch.arange(start=0, end=5, step=1)
print(X)

tensor([0, 1, 2, 3, 4])


In [15]:
X = torch.linspace(start=0.1, end=1, steps=10)
print(X)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


**Diagonal Matrix**

In [16]:
X = torch.diag(torch.ones(3))
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### **Tensor Type Conversion**

In [17]:
X = torch.arange(4)

In [18]:
# Converting to boolean type
print(X.bool())

tensor([False,  True,  True,  True])


In [19]:
# Converting to int16
print(X.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [20]:
# Converting to int64
print(X.long())

tensor([0, 1, 2, 3])


In [21]:
# Converting to float16
print(X.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [22]:
# Converting to float32
print(X.float())

tensor([0., 1., 2., 3.])


In [23]:
# Converting to float64
print(X.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


### **Array to Tensor Conversion and Vice-Versa**

In [24]:
import numpy as np

In [26]:
X_arr = np.zeros((5, 5))
print(X_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
# Array to Tensor
X = torch.from_numpy(X_arr)
print(X)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [30]:
 # Tensor to array
print(X.numpy())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### **Tensor Math and Comparison Operations**

In [31]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([9, 8, 7])

In [33]:
# Addition
Z1 = torch.add(X, Y)  # Z1 = X + Y
print(Z1)

tensor([10, 10, 10])


In [34]:
# Subtraction
Z2 = X - Y
print(Z2)

tensor([-8, -6, -4])


In [35]:
# Division
Z3 = torch.true_divide(X, Y)
print(Z3)

tensor([0.1111, 0.2500, 0.4286])


**Inplace Operation**

In [36]:
T = torch.zeros(3)
T.add_(X)
print(T)

tensor([1., 2., 3.])


In [37]:
# OR
T += X
print(T)

tensor([2., 4., 6.])


In [38]:
# Element-wise exponentiation
Z = X ** 2
print(Z)

tensor([1, 4, 9])


In [39]:
# Element-wise comparsion
X = X > 2
print(X)

tensor([False, False,  True])


**Matrix Multiplication**

In [40]:
X1 = torch.rand(2, 5)
X2 = torch.rand(5, 3)

Z3 = torch.mm(X1, X2)
print(Z3)

tensor([[1.2076, 1.5116, 2.0725],
        [1.0454, 1.2977, 2.0013]])


**Matrix Exponentiation**

In [41]:
X3 = torch.rand(4, 4)
print(X3.matrix_power(3))

tensor([[4.0420, 3.0551, 3.3016, 3.1973],
        [3.6235, 2.3460, 3.0922, 3.0385],
        [2.4076, 1.9510, 2.0648, 1.9359],
        [1.4799, 0.8432, 1.2923, 1.2510]])


**Element-wise Multiplication**

In [42]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([9, 8, 7])

Z4 = X * Y
print(Z4)

tensor([ 9, 16, 21])


**Dot Product**

In [43]:
Z5 = torch.dot(X, Y)

print(Z5)

tensor(46)


**Batch Matrix Multiplication**

In [45]:
batch = 32
c = 10
h = 20
w = 30 

T1 = torch.rand((batch, c, h))
T2 = torch.rand((batch, h, w))

T = torch.bmm(T1, T2)

In [46]:
print(T.shape)

torch.Size([32, 10, 30])


**Broadcasting**

In [48]:
X1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X2 = torch.tensor([1, 2, 3])

print(X1)
print(X2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])


In [49]:
Z = X1 - X2
print(Z)

tensor([[0, 0, 0],
        [3, 3, 3],
        [6, 6, 6]])


In [50]:
Z = X1 ** X2
print(Z)

tensor([[  1,   4,  27],
        [  4,  25, 216],
        [  7,  64, 729]])


**Summation of Row and Column Elements**

In [53]:
# Column element sum
print(torch.sum(X1, dim=0))

tensor([12, 15, 18])


In [54]:
# Row elements sum
print(torch.sum(X1, dim=1))

tensor([ 6, 15, 24])


In [55]:
# Summation of all elements
print(torch.sum(X1))

tensor(45)


**Finding the Maximum and Min Elements**

In [57]:
# Maximum element of a column
value, idx = torch.max(X1, dim=0)
print(value, idx)

tensor([7, 8, 9]) tensor([2, 2, 2])


In [59]:
value, idx = torch.min(X1, dim=0)
print(value, idx)

tensor([1, 2, 3]) tensor([0, 0, 0])


In [63]:
# Maximum element
print(X1)
m = torch.argmax(X1, dim=0)
print(m)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 2, 2])


In [64]:
# Index of Minimum element
print(torch.argmin(X1, dim=1))

tensor([0, 0, 0])


**Mean Value**

In [66]:
print(torch.mean(X1.float(), dim=0))

tensor([4., 5., 6.])


**Checking Equality**

In [67]:
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([1, 5, 10])

print(torch.eq(X1, X2))

tensor([ True, False, False])


**Sorting**

In [70]:
X1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sorted_X1, idx = torch.sort(X1, dim=0, descending=True)
print(sorted_X1)

tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])


**Clamping**

In [71]:
X1 = torch.tensor([[-1, 0, 4], [4, 5, 11]])
print(torch.clamp(X1, min=0, max=10))

tensor([[ 0,  0,  4],
        [ 4,  5, 10]])


**Checking if any value is `True`**

In [72]:
X = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
print(torch.any(X))

tensor(True)


**Checking if all value is `True`**

In [73]:
print(torch.all(X))

tensor(False)


### **Tensor Indexing**