<a href="https://colab.research.google.com/github/sabbir-ahmed12/pytorch-practice/blob/main/basic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Basics**
- Tensor initialization and manipulation.

In [74]:
import torch

### **Setting up device**

In [75]:
device = "cuda" if torch.cuda.is_available() else "cpu"

### **Tensor Initialization**

In [76]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, )
print(X)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [77]:
# Printing the data type
print(X.dtype)

torch.float32


In [78]:
# Printing the shape
print(X.shape)

torch.Size([2, 3])


In [79]:
# Printing if gradient is required
print(X.requires_grad)

False


**Empty Initialization (Random)**

In [80]:
X = torch.empty(size=(3, 3))
print(X)

tensor([[1.8308e-34, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16]])


**Zero Initialization**

In [81]:
X = torch.zeros((3, 3))
print(X)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**Random initialization from uniform distribution**

In [82]:
X = torch.rand((3, 3))
print(X)

tensor([[0.0199, 0.9503, 0.0949],
        [0.2596, 0.3932, 0.2099],
        [0.0530, 0.9474, 0.6684]])


**Ones Initialization**

In [83]:
X = torch.ones((3, 3))
print(X)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


**Identity Matrix**

In [84]:
X = torch.eye(3, 3)
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Some other methods**

In [85]:
X = torch.arange(start=0, end=5, step=1)
print(X)

tensor([0, 1, 2, 3, 4])


In [86]:
X = torch.linspace(start=0.1, end=1, steps=10)
print(X)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


**Diagonal Matrix**

In [87]:
X = torch.diag(torch.ones(3))
print(X)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### **Tensor Type Conversion**

In [88]:
X = torch.arange(4)

In [89]:
# Converting to boolean type
print(X.bool())

tensor([False,  True,  True,  True])


In [90]:
# Converting to int16
print(X.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [91]:
# Converting to int64
print(X.long())

tensor([0, 1, 2, 3])


In [92]:
# Converting to float16
print(X.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [93]:
# Converting to float32
print(X.float())

tensor([0., 1., 2., 3.])


In [94]:
# Converting to float64
print(X.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


### **Array to Tensor Conversion and Vice-Versa**

In [95]:
import numpy as np

In [96]:
X_arr = np.zeros((5, 5))
print(X_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [97]:
# Array to Tensor
X = torch.from_numpy(X_arr)
print(X)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [98]:
 # Tensor to array
print(X.numpy())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### **Tensor Math and Comparison Operations**

In [99]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([9, 8, 7])

In [100]:
# Addition
Z1 = torch.add(X, Y)  # Z1 = X + Y
print(Z1)

tensor([10, 10, 10])


In [101]:
# Subtraction
Z2 = X - Y
print(Z2)

tensor([-8, -6, -4])


In [102]:
# Division
Z3 = torch.true_divide(X, Y)
print(Z3)

tensor([0.1111, 0.2500, 0.4286])


**Inplace Operation**

In [103]:
T = torch.zeros(3)
T.add_(X)
print(T)

tensor([1., 2., 3.])


In [104]:
# OR
T += X
print(T)

tensor([2., 4., 6.])


In [105]:
# Element-wise exponentiation
Z = X ** 2
print(Z)

tensor([1, 4, 9])


In [106]:
# Element-wise comparsion
X = X > 2
print(X)

tensor([False, False,  True])


**Matrix Multiplication**

In [107]:
X1 = torch.rand(2, 5)
X2 = torch.rand(5, 3)

Z3 = torch.mm(X1, X2)
print(Z3)

tensor([[2.1954, 2.1640, 1.4954],
        [1.6238, 1.8665, 1.3530]])


**Matrix Exponentiation**

In [108]:
X3 = torch.rand(4, 4)
print(X3.matrix_power(3))

tensor([[1.4028, 2.7197, 2.3821, 0.8180],
        [1.5527, 2.6685, 2.5814, 0.9879],
        [2.0775, 3.5512, 3.2983, 1.1896],
        [2.7033, 4.0324, 3.8045, 1.3624]])


**Element-wise Multiplication**

In [109]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([9, 8, 7])

Z4 = X * Y
print(Z4)

tensor([ 9, 16, 21])


**Dot Product**

In [110]:
Z5 = torch.dot(X, Y)

print(Z5)

tensor(46)


**Batch Matrix Multiplication**

In [111]:
batch = 32
c = 10
h = 20
w = 30 

T1 = torch.rand((batch, c, h))
T2 = torch.rand((batch, h, w))

T = torch.bmm(T1, T2)

In [112]:
print(T.shape)

torch.Size([32, 10, 30])


**Broadcasting**

In [113]:
X1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X2 = torch.tensor([1, 2, 3])

print(X1)
print(X2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])


In [114]:
Z = X1 - X2
print(Z)

tensor([[0, 0, 0],
        [3, 3, 3],
        [6, 6, 6]])


In [115]:
Z = X1 ** X2
print(Z)

tensor([[  1,   4,  27],
        [  4,  25, 216],
        [  7,  64, 729]])


**Summation of Row and Column Elements**

In [116]:
# Column element sum
print(torch.sum(X1, dim=0))

tensor([12, 15, 18])


In [117]:
# Row elements sum
print(torch.sum(X1, dim=1))

tensor([ 6, 15, 24])


In [118]:
# Summation of all elements
print(torch.sum(X1))

tensor(45)


**Finding the Maximum and Min Elements**

In [119]:
# Maximum element of a column
value, idx = torch.max(X1, dim=0)
print(value, idx)

tensor([7, 8, 9]) tensor([2, 2, 2])


In [120]:
value, idx = torch.min(X1, dim=0)
print(value, idx)

tensor([1, 2, 3]) tensor([0, 0, 0])


In [121]:
# Maximum element
print(X1)
m = torch.argmax(X1, dim=0)
print(m)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 2, 2])


In [122]:
# Index of Minimum element
print(torch.argmin(X1, dim=1))

tensor([0, 0, 0])


**Mean Value**

In [123]:
print(torch.mean(X1.float(), dim=0))

tensor([4., 5., 6.])


**Checking Equality**

In [124]:
X1 = torch.tensor([1, 2, 3])
X2 = torch.tensor([1, 5, 10])

print(torch.eq(X1, X2))

tensor([ True, False, False])


**Sorting**

In [125]:
X1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sorted_X1, idx = torch.sort(X1, dim=0, descending=True)
print(sorted_X1)

tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])


**Clamping**

In [126]:
X1 = torch.tensor([[-1, 0, 4], [4, 5, 11]])
print(torch.clamp(X1, min=0, max=10))

tensor([[ 0,  0,  4],
        [ 4,  5, 10]])


**Checking if any value is `True`**

In [127]:
X = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
print(torch.any(X))

tensor(True)


**Checking if all value is `True`**

In [128]:
print(torch.all(X))

tensor(False)


### **Tensor Indexing**

In [130]:
BATCH_SIZE = 16
FEATURES = 32

X = torch.rand((BATCH_SIZE, FEATURES))

# Printing all features of first example
print(X[0])

tensor([0.7732, 0.1322, 0.1152, 0.0966, 0.8115, 0.0472, 0.0688, 0.8660, 0.5093,
        0.1987, 0.2781, 0.7062, 0.7457, 0.0135, 0.1637, 0.7440, 0.6444, 0.2140,
        0.6242, 0.7519, 0.4379, 0.5547, 0.7049, 0.8126, 0.4494, 0.7261, 0.2362,
        0.1748, 0.9314, 0.6059, 0.0467, 0.3298])


In [131]:
# Printing first feature of all examples
print(X[0, :])

tensor([0.7732, 0.1322, 0.1152, 0.0966, 0.8115, 0.0472, 0.0688, 0.8660, 0.5093,
        0.1987, 0.2781, 0.7062, 0.7457, 0.0135, 0.1637, 0.7440, 0.6444, 0.2140,
        0.6242, 0.7519, 0.4379, 0.5547, 0.7049, 0.8126, 0.4494, 0.7261, 0.2362,
        0.1748, 0.9314, 0.6059, 0.0467, 0.3298])


In [132]:
# Printing 0 to 10 features of 3rd example
print(X[2, 0:10])

tensor([0.5396, 0.8080, 0.1405, 0.2427, 0.8356, 0.6732, 0.7916, 0.8963, 0.5015,
        0.7053])


### **Tensor Reshaping**

In [139]:
X = torch.arange(9)

In [140]:
print(X.reshape(3, 3))  

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [141]:
# To store contiguously
print(X.view(3, 3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [143]:
# Transposing tensor
X = X.reshape(3, 3)
print(X.t())

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


**Concatenating Tensors**

In [144]:
X1 = torch.rand((2, 5))
X2 = torch.rand((2, 5))

print(torch.cat((X1, X2), dim=0))


tensor([[0.5621, 0.3911, 0.6250, 0.3655, 0.0484],
        [0.0569, 0.8404, 0.2008, 0.0706, 0.9036],
        [0.1083, 0.7291, 0.0094, 0.2404, 0.2818],
        [0.3422, 0.1029, 0.2514, 0.9950, 0.5089]])


**Flattening Tensor**

In [145]:
X = torch.rand((2, 5))
print(X.view(-1))

tensor([0.9743, 0.2600, 0.1126, 0.9935, 0.7579, 0.0436, 0.0197, 0.8448, 0.4661,
        0.0154])


In [147]:
BATCH = 8
X = torch.rand((BATCH, 2, 5))

# Flattening only the last two dimensions
print(X.view(BATCH, -1).shape)

torch.Size([8, 10])


**Altering Dimensions**

In [149]:
X = torch.rand((8, 2, 5))

# Keeping the first dimension same
Z = X.permute(0, 2, 1)
print(Z.shape)

torch.Size([8, 5, 2])


**Reducing Dimensions**

In [152]:
X = torch.tensor([[[1, 2, 3]]])
print(X.shape)

torch.Size([1, 1, 3])


In [154]:
print(X)

tensor([[[1, 2, 3]]])


In [153]:
Z = X.squeeze(dim=0)
print(Z.shape)

torch.Size([1, 3])


In [155]:
print(Z)

tensor([[1, 2, 3]])
